trigger:
- main

variables:
  azureServiceConnection: 'azure-manual-connection'  # Azure RM connection for ACI deploy
  acrName: 'myazureacr2'
  resourceGroupName: 'kml_rg_main-c706ef5731324a43'
  aciContainerGroupName: 'hello-world-app-container'
  location: 'westus2'  # or your region
  registryPassword: '$(acrPassword)'  # secret variable in pipeline

stages:
- stage: BuildAndPush
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: BuildAndPushJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Build and Push Image to ACR'
      inputs:
        command: buildAndPush
        containerRegistry: 'azure-arm-connection'   # service connection name
        repository: '$(aciContainerGroupName)'
        dockerfile: 'Dockerfile'
        tags: |
          $(Build.BuildId)
          latest

- stage: Deploy
  dependsOn: BuildAndPush
  jobs:
  - job: DeployJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy Container to ACI'
      inputs:
        azureSubscription: '$(azureServiceConnection)'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az container create \
            --resource-group $(resourceGroupName) \
            --name $(aciContainerGroupName) \
            --image $(acrName).azurecr.io/$(aciContainerGroupName):$(Build.BuildId) \
            --dns-name-label $(aciContainerGroupName) \
            --ports 80 \
            --location $(location) \
            --cpu 1 \
            --memory 1.5 \
            --registry-login-server $(acrName).azurecr.io \
            --registry-username $(acrName) \
            --registry-password $(registryPassword)
