# Trigger on every push to the main branch
trigger:
  - main

# Variables
variables:
  azureServiceConnection: 'azure-arm-connection'           # Name of your Azure DevOps Service Connection
  acrName: 'myazureacr2'                                   # Your Azure Container Registry name
  imageName: 'hello-world-app:$(Build.BuildId)'            # Image name with build ID
  resourceGroupName: 'kml_rg_main-c706ef5731324a43'        # Resource Group
  aciContainerGroupName: 'hello-world-app-container'       # ACI Container Group name
  location: 'westus2'                                      # Azure region
  registryPassword: ''                                     # Set this as a secret variable in Azure DevOps

stages:

- stage: BuildAndPush
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: BuildAndPushJob
    displayName: 'Build and Push'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Build and Push Image to ACR'
      inputs:
        command: 'buildAndPush'
        containerRegistry: '$(azureServiceConnection)'
        repository: '$(aciContainerGroupName)'             # Repo in ACR
        dockerfile: 'Dockerfile'
        tags: |
          $(Build.BuildId)
          latest

- stage: Deploy
  displayName: 'Deploy to Azure Container Instances'
  dependsOn: BuildAndPush
  jobs:
  - job: DeployJob
    displayName: 'Deploy to ACI'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy Container to ACI'
      inputs:
        azureSubscription: '$(azureServiceConnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az container create \
            --resource-group $(resourceGroupName) \
            --name $(aciContainerGroupName) \
            --image $(acrName).azurecr.io/$(aciContainerGroupName):$(Build.BuildId) \
            --dns-name-label $(aciContainerGroupName) \
            --ports 80 \
            --location $(location) \
            --cpu 1 \
            --memory 1.5 \
            --registry-login-server $(acrName).azurecr.io \
            --registry-username $(acrName) \
            --registry-password $(registryPassword)
