trigger:
- main

variables:
  acrName: 'myazureacr2'  # ACR name
  acrUsername: 'myazureacr2' # admin username from ACR
  aciContainerGroupName: 'hello-world-app-container'
  resourceGroupName: 'kml_rg_main-c706ef5731324a43'
  location: 'westus2'
  imageName: 'hello-world-app:$(Build.BuildId)' 

stages:
- stage: BuildAndPush
  displayName: 'Build and Push Docker Image'
  jobs:
  - job: BuildAndPushJob
    displayName: 'Build and Push'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Login to ACR'
      inputs:
        command: 'login'
        containerRegistry: '$(acrName).azurecr.io'
        username: '$(acrUsername)'
        password: '$(acrPassword)'  # define as secret pipeline variable
    - task: Docker@2
      displayName: 'Build and Push Image'
      inputs:
        command: 'buildAndPush'
        repository: '$(aciContainerGroupName)'
        dockerfile: 'Dockerfile'
        tags: |
          $(Build.BuildId)
          latest
        containerRegistry: '$(acrName).azurecr.io'

- stage: Deploy
  displayName: 'Deploy to Azure Container Instances'
  dependsOn: BuildAndPush
  jobs:
  - job: DeployJob
    displayName: 'Deploy to ACI'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy Container to ACI'
      inputs:
        azureSubscription: 'azure-manual-connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az container create \
            --resource-group $(resourceGroupName) \
            --name $(aciContainerGroupName) \
            --image $(acrName).azurecr.io/$(aciContainerGroupName):$(Build.BuildId) \
            --dns-name-label $(aciContainerGroupName) \
            --ports 80 \
            --location $(location) \
            --cpu 1 \
            --memory 1.5 \
            --registry-login-server $(acrName).azurecr.io \
            --registry-username $(acrUsername) \
            --registry-password $(acrPassword)
